#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: Sign Well
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  We use state of the art machine learning to help people communicate with the over 72 million deaf or hard of hearing people that use sign language. 
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  Sign language plays a crucial role in fostering communication and inclusivity for the global deaf and hard-of-hearing community. As a distinct and expressive form of communication, sign language enables individuals who may not be able to hear or speak to convey their thoughts, emotions, and ideas effectively. Its significance lies not only in providing a means of communication but also in promoting cultural identity and community cohesion among deaf individuals. Just like spoken languages, sign languages are diverse and vary across different regions and communities, reflecting the rich cultural and linguistic diversity within the deaf world. Recognizing and embracing the importance of sign language contributes to the creation of an inclusive society where everyone, regardless of their hearing ability, can participate fully in various aspects of life, from education and employment to social interactions.

One of the most natural and direct ways for deaf and hearing individuals to communicate is through sign language.  We're here to help make learning sign language easier and faster.


  

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: syap47@gmail.com
org_street_address:  #Please include suite number on the line below
org_address_suite: 23 Corporate Plaza Drive, Suite 150-88
org_city: Newport Beach
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  92660
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  

#SOCIAL MEDIA
org_twitter_username: signwell
org_facebook_username: signwell
org_instagram_username: signwell

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
is_501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#COLOR SCHEME
#Select one of the five color schemes (default, one, two, three, or four)
color_scheme: one

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
